# Generated by Django 3.2.9 on 2021-12-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='crete_date',
            new_name='create_date',
        ),
    ]
